repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Gitleaks Secret Scanner
        entry: gitleaks detect --redact --exit-code
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args:
          - "--unsafe"
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # - repo: https://github.com/psf/black-pre-commit-mirror
  #   rev: 24.8.0
  #   hooks:
  #     - id: black
  #       language_version: python3.11

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       args: ["--profile", "black"]
