# Generated by Django 5.1.1 on 2025-08-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag_sample_app", "0008_rename_ai_response_chathistory_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="chathistory",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddIndex(
            model_name="chathistory",
            index=models.Index(
                fields=["thread_id", "timestamp"], name="rag_sample__thread__6f0286_idx"
            ),
        ),
    ]
