name: Build, Push and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # デプロイをトリガーするブランチを指定

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Google Cloud 認証を設定
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          setup-docker: true

      - name: Google Cloud SDK を設定
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'aimensetsu'

      - name: Docker イメージをビルド
        run: |
          docker build -t asia-northeast1-docker.pkg.dev/aimensetsu/rag-sample-app/rag-sample-app:latest .

      - name: Docker イメージをプッシュ
        run: |
          docker push asia-northeast1-docker.pkg.dev/aimensetsu/rag-sample-app/rag-sample-app:latest

      - name: 環境変数を設定
        run: |
          echo "${{ secrets.DEPLOY_ENVIRONMENT }}" > env_vars.txt
          ENV_VARS=$(grep -v '^#' env_vars.txt | xargs | sed 's/ /,/g')

      - name: Cloud Run にデプロイ
        run: |
          gcloud run deploy rag-sample-app \
            --image=asia-northeast1-docker.pkg.dev/aimensetsu/rag-sample-app/rag-sample-app:latest \
            --region=asia-northeast1 \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars "$ENV_VARS"

      - name: 一時ファイルを削除
        run: |
          rm env_vars.txt
